### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by adrianmihalko** [a-sync/rtlmost-downloader#7]
Szia,

Telepítés után:

```
$ rtlmost-downloader
/usr/bin/env: ‘node\r’: No such file or directory
```
<img width="645" alt="screenshot 2018-12-09 at 16 07 12" src="https://user-images.githubusercontent.com/733361/49699063-89e22700-fbcc-11e8-9351-c51ea34a3556.png">

Úgy néz ki, hogy Windows fájlvégződésekkel lett elmentve. Átkonvertálva a fájlt Unix végződésűre már nem adja ezt a hibát, de van újabb:

```
$ node /usr/bin/rtlmost-downloader 
/usr/lib/node_modules/rtlmost-downloader/node_modules/got/source/create.js:61
	got.stream = (url, options) => got(url, {...options, stream: true});
	                                                                  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/rtlmost-downloader/node_modules/got/source/index.js:3:16)


```

**Comment by a-sync** [comment]
Szia,
global-ként telepítetted igaz? Úgy tűnik win sortörésekkel került fel npm-re. :(
Milyen node verziód van? 8.3.0 -tól támogatott a `...` operátor amire a hiba utal.  
`node -v`

**Comment by adrianmihalko** [comment]
Szia, igazad van, egy frissebb node verzió telepítése után simán megy az app. :)

**Comment by a-sync** [comment]
👍
